name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21"

            - name: Install bats
              uses: bats-core/bats-action@3.0.1

            - name: Check go fmt
              run: go fmt ./... && git diff --exit-code

            - name: Download dependencies
              run: go mod download

            - name: Verify dependencies
              run: go mod verify

            - name: Check go.mod and go.sum are up to date
              run: |
                  go mod tidy
                  git diff --exit-code go.mod go.sum

            - name: Run go vet
              run: go vet ./...

            - name: Build
              run: go build

            - name: Run go tests
              run: go test -v ./...

            - name: Setup integration test dependencies
              run: ./integration_tests/setup.sh

            - name: Run bats integration tests
              # fixes open stdin in GH actions breaking stdin detection, see:
              # https://github.com/actions/runner-images/issues/10959
              # https://github.com/janpieterz/prettier-cli-repro/pull/2/files
              shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
              run: bats integration_tests
